name: Run Example Script

on:
  workflow_dispatch:

jobs:
  run-example:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install image-ascii==0.1.0

    - name: Run example script
      run: |
        python example.py
