name: Run Image to ASCII

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  image-to-ascii:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install asciimj
        pip install pillow

    - name: Run image to ASCII script
      run: python example.py

    - name: Upload ASCII art file
      uses: actions/upload-artifact@v3
      with:
        name: ascii-art
        path: image.txt  # 替换为你的实际 .txt 文件路径
